name: Continuous Integration

on:
  push:
    branches:
      - develop
      - feature/*

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        node-version: ['14']
    name: "[v${{ matrix.node-version }}] prepare"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile

  check:
    runs-on: ubuntu-20.04
    needs: prepare
    strategy:
      matrix:
        node-version: ['14']
    name: "[v${{ matrix.node-version }}] check"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Lint
        run: |
          yarn lint

      # - name: Test
      #   env:
      #     CI: 1
      #   run: |
      #     yarn test

      # - name: Submit coverage
      #   uses: codecov/codecov-action@v1
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}

  build-and-run:
    runs-on: ubuntu-20.04
    needs: prepare
    strategy:
      matrix:
        node-version: ['14']
    name: "[v${{ matrix.node-version }}] build"

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2-beta
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      - name: Cache next
        id: cache-next
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          yarn install --frozen-lockfile

      - name: Build
        run: |
          yarn build

      - name: Run & check status code
        run: |
          yarn start &
          sleep 5
          curl http://localhost:3000/api/_health > /dev/null

  build-docker:
    name: Build docker
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2

      -
        name: Repo metadata
        id: repo
        uses: actions/github-script@v3
        with:
          script: |
            const repo = await github.repos.get(context.repo)
            return repo.data

      -
        name: Prepare
        id: prep
        run: |
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      -
        name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      -
        name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          # load: true
          tags: ghcr.io/bratteng/salottotrondheim.no:develop
          cache-from: type=local,src=${{ github.workspace }}/.buildx-cache
          cache-to: type=local,mode=max,dest=${{ github.workspace }}/.buildx-cache
          build-args: |
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            FONTAWESOME_TOKEN=${{ secrets.FONTAWESOME_TOKEN }}
          labels: |
            org.opencontainers.image.url=${{ fromJson(steps.repo.outputs.result).html_url }}
            org.opencontainers.image.source=${{ fromJson(steps.repo.outputs.result).clone_url }}
            org.opencontainers.image.version=develop
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
            org.opencontainers.image.licenses=${{ fromJson(steps.repo.outputs.result).license.spdx_id }}
