name: continuous-integration

on:
  pull_request_target:
  push:
    branches:
      - develop
      - feature/**
      - chore/**

env:
  CI: true
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
  FONTAWESOME_TOKEN: ${{ secrets.FONTAWESOME_TOKEN }}

jobs:
  prepare:
    runs-on: ubuntu-20.04
    name: Prepare

    steps:
      -
        if: ${{ github.actor == 'dependabot[bot]' }}
        name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      -
        if: ${{ github.actor != 'dependabot[bot]' }}
        name: Checkout code
        uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 22


      -
        name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4.2.1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      -
        name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          pnpm install --frozen-lockfile

  check:
    runs-on: ubuntu-20.04
    needs: prepare
    name: Check

    steps:
      -
        if: ${{ github.actor == 'dependabot[bot]' }}
        name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      -
        if: ${{ github.actor != 'dependabot[bot]' }}
        name: Checkout code
        uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 22

      -
        name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4.2.1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      -
        name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          pnpm install --frozen-lockfile

      -
        name: Lint
        run: |
          pnpm run lint

  build-and-run:
    runs-on: ubuntu-20.04
    needs: prepare
    name: Build

    steps:
      -
        if: ${{ github.actor == 'dependabot[bot]' }}
        name: Checkout code
        uses: actions/checkout@v4.2.2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      -
        if: ${{ github.actor != 'dependabot[bot]' }}
        name: Checkout code
        uses: actions/checkout@v4.2.2

      - uses: pnpm/action-setup@v4.1.0
      - uses: actions/setup-node@v4.2.0
        with:
          node-version: 22

      -
        name: Cache node_modules
        id: cache-node_modules
        uses: actions/cache@v4.2.1
        with:
          path: node_modules
          key: ${{ runner.os }}-node_modules-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-node_modules-
            ${{ runner.os }}-

      -
        name: Cache next
        id: cache-next
        uses: actions/cache@v4.2.1
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/pnpm-lock.yaml') }}

      -
        name: Install dependencies
        if: steps.cache-node_modules.outputs.cache-hit != 'true'
        run: |
          pnpm install --frozen-lockfile

      -
        name: Build
        run: |
          pnpm run build

      -
        name: Run & check status code
        run: |
          pnpm run start &
          sleep 5
          curl --silent --fail http://localhost:3000/api/_health

  dependabot:
    needs:
      - check
      - build-and-run
    uses: ./.github/workflows/dependabot-automerge.yaml
