name: continuous-security

on:
  workflow_dispatch:
  schedule:
    # run every day at 1AM
    - cron: "0 1 * * *"

jobs:
  dockerscan:
    name: Docker security scan
    runs-on: ubuntu-20.04
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v2

      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      -
        name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      -
        name: Docker build
        run: |
          docker buildx build . --load \
            --tag image:${{ github.sha }} \
            --cache-to=type=local,dest=/tmp/.buildx-cache \
            --cache-from=type=local,src=/tmp/.buildx-cache \
            --build-arg NPM_TOKEN=${{ secrets.NPM_TOKEN }} \
            --build-arg FONTAWESOME_TOKEN=${{ secrets.FONTAWESOME_TOKEN }}

      -
        name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.0.19
        with:
          image-ref: image:${{ github.sha }}
          format: table
          exit-code: 1
          ignore-unfixed: true
          severity: CRITICAL,HIGH
