name: release

on:
  workflow_dispatch:
    inputs:
      app_env:
        description: Application enviornment to build next.js for
        required: true
        default: 'production'
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    outputs:
      metadata: ${{ steps.docker_meta.outputs.json }}
    steps:
      -
        name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4.0.1
        with:
          images: ghcr.io/${{ github.repository }}
          flavor: |
            latest=${{ github.event.inputs.app_env == 'production' }}
          tags: |
            type=sha
            type=ref,event=tag

      -
        name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.0.0
        with:
          install: true

      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v3.1.1
        with:
          push: true
          builder: ${{ steps.buildx.outputs.name }}
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha
          build-args: |
            APP_ENV=${{ github.event.inputs.app_env }}
            NPM_TOKEN=${{ secrets.NPM_TOKEN }}
            FONTAWESOME_TOKEN=${{ secrets.FONTAWESOME_TOKEN }}

  deploy:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      -
        uses: actions/checkout@v3.0.2
        with:
          repository: omBratteng/salotto-k8s-config
          ref: main
          ssh-key: ${{ secrets.K8S_REPO_SECRET }}

      -
        run: |
          kustomize edit set image salotto-web=${{ fromJSON(needs.build.outputs.metadata).tags[0] }}

      -
        run: |
          git config --local user.name "${{ github.actor }}"
          git config --local user.email "106002604+ombratteng-gitops-bot@users.noreply.github.com"
          git add -A
          echo $(git status)
          git commit -m "set tag to \`$(git rev-parse --short HEAD)\`"
          git push

